data_template = {
    'Gravesite #': '',
    'Marker Type': '',
    'Emblem1': '',
    'Emblem2': '',
    'First Name': '',
    'Middle Name': '',
    'Last Name': '',
    'Suffix': '',
    'Location': '',
    'Rank': '',
    'Rank2': '',
    'Rank3': '',
    'Branch': '',
    'Branch2': '',
    'Branch3': '',
    'Branch-Unit_CustomV': '',
    'War': '',
    'War2': '',
    'War3': '',
    'War4': '',
    'BirthDate': '',
    'DeathDate': '',
    'Award': '',
    'Award2': '',
    'Award3': '',
    'Award4': '',
    'Award5': '',
    'Award6': '',
    'Award7': '',
    'Awards_Custom': '',
    'Inscription': '',

    'First Name Spouse/Dependent': '',
    'Middle Name Spouse/Dependent': '',
    'Last Name Spouse/Dependent': '',
    'Suffix Spouse/Dependent': '',
    'LocationS_D': '',
    'RankS_D': '',
    'Rank2S_D': '',
    'Rank3S_D': '',
    'BranchS_D': '',
    'Branch2S_D': '',
    'Branch3S_D': '',
    'Branch-Unit_CustomS_D': '',
    'WarS_D': '',
    'War2S_D': '',
    'War3S_D': '',
    'War4S_D': '',
    'BirthDateS_D': '',
    'DeathDateS_D': '',
    'AwardS_D': '',
    'Award2S_D': '',
    'Award3S_D': '',
    'Award4S_D': '',
    'Award5S_D': '',
    'Award6S_D': '',
    'Award7S_D': '',
    'Awards_CustomS_D': '',
    'InscriptionS_D': '',

    'FirstNameS_D_2': '',
    'MiddleNameS_D_2': '',
    'LastNameS_D_2': '',
    'SuffixS_D_2': '',
    'LocationS_D_2': '',
    'RankS_D_2': '',
    'BranchS_D_2': '',
    'WarS_D_2': '',
    'BirthDateS_D_2': '',
    'DeathDateS_D_2': '',
    'AwardS_D_2': '',
    'InscriptionS_D_2': '',

    'FirstNameS_D_3': '',
    'MiddleNameS_D_3': '',
    'LastNameS_D_3': '',
    'SuffixS_D_3': '',
    'LocationS_D_3': '',
    'RankS_D_3': '',
    'BranchS_D_3': '',
    'WarS_D_3': '',
    'BirthDateS_D_3': '',
    'DeathDateS_D_3': '',
    'AwardS_D_3': '',
    'InscriptionS_D_3': '',

    'FirstNameS_D_4': '',
    'MiddleNameS_D_4': '',
    'LastNameS_D_4': '',
    'SuffixS_D_4': '',
    'LocationS_D_4': '',
    'RankS_D_4': '',
    'BranchS_D_4': '',
    'WarS_D_4': '',
    'BirthDateS_D_4': '',
    'DeathDateS_D_4': '',
    'AwardS_D_4': '',
    'InscriptionS_D_4': '',

    'FirstNameS_D_5': '',
    'MiddleNameS_D_5': '',
    'LastNameS_D_5': '',
    'SuffixS_D_5': '',
    'LocationS_D_5': '',
    'BirthDateS_D_5': '',
    'DeathDateS_D_5': '',

    'FirstNameS_D_6': '',
    'MiddleNameS_D_6': '',
    'LastNameS_D_6': '',
    'SuffixS_D_6': '',
    'LocationS_D_6': '',
    'BirthDateS_D_6': '',
    'DeathDateS_D_6': ''
}